// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const allTitleBridgeLoc = `-- name: AllTitleBridgeLoc :many
SELECT 
    mtbc.id,
    mt.name AS title_name,
    c.tagName AS category_name,
    c.color AS category_color
FROM MissionTitleBridgeCategory mtbc
LEFT JOIN MissionTitle mt ON mtbc.missionTitleId = mt.id
LEFT JOIN Category c ON mtbc.categoryId = c.id
`

type AllTitleBridgeLocRow struct {
	ID            string
	TitleName     sql.NullString
	CategoryName  sql.NullString
	CategoryColor sql.NullString
}

func (q *Queries) AllTitleBridgeLoc(ctx context.Context) ([]AllTitleBridgeLocRow, error) {
	rows, err := q.db.QueryContext(ctx, allTitleBridgeLoc)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AllTitleBridgeLocRow
	for rows.Next() {
		var i AllTitleBridgeLocRow
		if err := rows.Scan(
			&i.ID,
			&i.TitleName,
			&i.CategoryName,
			&i.CategoryColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
