// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.12.4
// source: stack.proto

package gen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StackService_AddStack_FullMethodName    = "/peripheral_pb.StackService/AddStack"
	StackService_DeleteStack_FullMethodName = "/peripheral_pb.StackService/DeleteStack"
	StackService_PushStacks_FullMethodName  = "/peripheral_pb.StackService/PushStacks"
)

// StackServiceClient is the client API for StackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 定義服務接口
type StackServiceClient interface {
	// Server-side
	AddStack(ctx context.Context, in *Location, opts ...grpc.CallOption) (*Empty, error)
	// Server-side
	DeleteStack(ctx context.Context, in *Location, opts ...grpc.CallOption) (*Empty, error)
	// Client-side Streaming: Client 持續發送，Server 接收完回傳一個結果
	PushStacks(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StackMapResponse, Empty], error)
}

type stackServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStackServiceClient(cc grpc.ClientConnInterface) StackServiceClient {
	return &stackServiceClient{cc}
}

func (c *stackServiceClient) AddStack(ctx context.Context, in *Location, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, StackService_AddStack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stackServiceClient) DeleteStack(ctx context.Context, in *Location, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, StackService_DeleteStack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stackServiceClient) PushStacks(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StackMapResponse, Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StackService_ServiceDesc.Streams[0], StackService_PushStacks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StackMapResponse, Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StackService_PushStacksClient = grpc.ClientStreamingClient[StackMapResponse, Empty]

// StackServiceServer is the server API for StackService service.
// All implementations must embed UnimplementedStackServiceServer
// for forward compatibility.
//
// 定義服務接口
type StackServiceServer interface {
	// Server-side
	AddStack(context.Context, *Location) (*Empty, error)
	// Server-side
	DeleteStack(context.Context, *Location) (*Empty, error)
	// Client-side Streaming: Client 持續發送，Server 接收完回傳一個結果
	PushStacks(grpc.ClientStreamingServer[StackMapResponse, Empty]) error
	mustEmbedUnimplementedStackServiceServer()
}

// UnimplementedStackServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStackServiceServer struct{}

func (UnimplementedStackServiceServer) AddStack(context.Context, *Location) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddStack not implemented")
}
func (UnimplementedStackServiceServer) DeleteStack(context.Context, *Location) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteStack not implemented")
}
func (UnimplementedStackServiceServer) PushStacks(grpc.ClientStreamingServer[StackMapResponse, Empty]) error {
	return status.Error(codes.Unimplemented, "method PushStacks not implemented")
}
func (UnimplementedStackServiceServer) mustEmbedUnimplementedStackServiceServer() {}
func (UnimplementedStackServiceServer) testEmbeddedByValue()                      {}

// UnsafeStackServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StackServiceServer will
// result in compilation errors.
type UnsafeStackServiceServer interface {
	mustEmbedUnimplementedStackServiceServer()
}

func RegisterStackServiceServer(s grpc.ServiceRegistrar, srv StackServiceServer) {
	// If the following call panics, it indicates UnimplementedStackServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StackService_ServiceDesc, srv)
}

func _StackService_AddStack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Location)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StackServiceServer).AddStack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StackService_AddStack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StackServiceServer).AddStack(ctx, req.(*Location))
	}
	return interceptor(ctx, in, info, handler)
}

func _StackService_DeleteStack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Location)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StackServiceServer).DeleteStack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StackService_DeleteStack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StackServiceServer).DeleteStack(ctx, req.(*Location))
	}
	return interceptor(ctx, in, info, handler)
}

func _StackService_PushStacks_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StackServiceServer).PushStacks(&grpc.GenericServerStream[StackMapResponse, Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StackService_PushStacksServer = grpc.ClientStreamingServer[StackMapResponse, Empty]

// StackService_ServiceDesc is the grpc.ServiceDesc for StackService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StackService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "peripheral_pb.StackService",
	HandlerType: (*StackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddStack",
			Handler:    _StackService_AddStack_Handler,
		},
		{
			MethodName: "DeleteStack",
			Handler:    _StackService_DeleteStack_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PushStacks",
			Handler:       _StackService_PushStacks_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "stack.proto",
}
