// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: stack.proto

package gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 貨物資訊
type Cargo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"` // 對應你的 json.RawMessage
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cargo) Reset() {
	*x = Cargo{}
	mi := &file_stack_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cargo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cargo) ProtoMessage() {}

func (x *Cargo) ProtoReflect() protoreflect.Message {
	mi := &file_stack_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cargo.ProtoReflect.Descriptor instead.
func (*Cargo) Descriptor() ([]byte, []int) {
	return file_stack_proto_rawDescGZIP(), []int{0}
}

func (x *Cargo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Cargo) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 堆棧資訊
type Stack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Disable       bool                   `protobuf:"varint,3,opt,name=disable,proto3" json:"disable,omitempty"`
	StackCount    int32                  `protobuf:"varint,4,opt,name=stack_count,json=stackCount,proto3" json:"stack_count,omitempty"`
	Heights       []int32                `protobuf:"varint,5,rep,packed,name=heights,proto3" json:"heights,omitempty"` // repeated 代表 slice
	Cargo         []*Cargo               `protobuf:"bytes,6,rep,name=cargo,proto3" json:"cargo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stack) Reset() {
	*x = Stack{}
	mi := &file_stack_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stack) ProtoMessage() {}

func (x *Stack) ProtoReflect() protoreflect.Message {
	mi := &file_stack_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stack.ProtoReflect.Descriptor instead.
func (*Stack) Descriptor() ([]byte, []int) {
	return file_stack_proto_rawDescGZIP(), []int{1}
}

func (x *Stack) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stack) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Stack) GetDisable() bool {
	if x != nil {
		return x.Disable
	}
	return false
}

func (x *Stack) GetStackCount() int32 {
	if x != nil {
		return x.StackCount
	}
	return 0
}

func (x *Stack) GetHeights() []int32 {
	if x != nil {
		return x.Heights
	}
	return nil
}

func (x *Stack) GetCargo() []*Cargo {
	if x != nil {
		return x.Cargo
	}
	return nil
}

// 整個 Map 的包裝
type StackMapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InfoMap       map[string]*Stack      `protobuf:"bytes,1,rep,name=info_map,json=infoMap,proto3" json:"info_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StackMapResponse) Reset() {
	*x = StackMapResponse{}
	mi := &file_stack_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StackMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StackMapResponse) ProtoMessage() {}

func (x *StackMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stack_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StackMapResponse.ProtoReflect.Descriptor instead.
func (*StackMapResponse) Descriptor() ([]byte, []int) {
	return file_stack_proto_rawDescGZIP(), []int{2}
}

func (x *StackMapResponse) GetInfoMap() map[string]*Stack {
	if x != nil {
		return x.InfoMap
	}
	return nil
}

// 空訊息，用於 WatchStacks 請求
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_stack_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_stack_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_stack_proto_rawDescGZIP(), []int{3}
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locationid    string                 `protobuf:"bytes,1,opt,name=locationid,proto3" json:"locationid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_stack_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_stack_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_stack_proto_rawDescGZIP(), []int{4}
}

func (x *Location) GetLocationid() string {
	if x != nil {
		return x.Locationid
	}
	return ""
}

var File_stack_proto protoreflect.FileDescriptor

const file_stack_proto_rawDesc = "" +
	"\n" +
	"\vstack.proto\x12\rperipheral_pb\"3\n" +
	"\x05Cargo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bmetadata\x18\x02 \x01(\fR\bmetadata\"\xbe\x01\n" +
	"\x05Stack\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\adisable\x18\x03 \x01(\bR\adisable\x12\x1f\n" +
	"\vstack_count\x18\x04 \x01(\x05R\n" +
	"stackCount\x12\x18\n" +
	"\aheights\x18\x05 \x03(\x05R\aheights\x12*\n" +
	"\x05cargo\x18\x06 \x03(\v2\x14.peripheral_pb.CargoR\x05cargo\"\xad\x01\n" +
	"\x10StackMapResponse\x12G\n" +
	"\binfo_map\x18\x01 \x03(\v2,.peripheral_pb.StackMapResponse.InfoMapEntryR\ainfoMap\x1aP\n" +
	"\fInfoMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.peripheral_pb.StackR\x05value:\x028\x01\"\a\n" +
	"\x05Empty\"*\n" +
	"\bLocation\x12\x1e\n" +
	"\n" +
	"locationid\x18\x01 \x01(\tR\n" +
	"locationid2\xce\x01\n" +
	"\fStackService\x129\n" +
	"\bAddStack\x12\x17.peripheral_pb.Location\x1a\x14.peripheral_pb.Empty\x12<\n" +
	"\vDeleteStack\x12\x17.peripheral_pb.Location\x1a\x14.peripheral_pb.Empty\x12E\n" +
	"\n" +
	"PushStacks\x12\x1f.peripheral_pb.StackMapResponse\x1a\x14.peripheral_pb.Empty(\x01B Z\x1ekenmec/peripheral/protoGen;genb\x06proto3"

var (
	file_stack_proto_rawDescOnce sync.Once
	file_stack_proto_rawDescData []byte
)

func file_stack_proto_rawDescGZIP() []byte {
	file_stack_proto_rawDescOnce.Do(func() {
		file_stack_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stack_proto_rawDesc), len(file_stack_proto_rawDesc)))
	})
	return file_stack_proto_rawDescData
}

var file_stack_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_stack_proto_goTypes = []any{
	(*Cargo)(nil),            // 0: peripheral_pb.Cargo
	(*Stack)(nil),            // 1: peripheral_pb.Stack
	(*StackMapResponse)(nil), // 2: peripheral_pb.StackMapResponse
	(*Empty)(nil),            // 3: peripheral_pb.Empty
	(*Location)(nil),         // 4: peripheral_pb.Location
	nil,                      // 5: peripheral_pb.StackMapResponse.InfoMapEntry
}
var file_stack_proto_depIdxs = []int32{
	0, // 0: peripheral_pb.Stack.cargo:type_name -> peripheral_pb.Cargo
	5, // 1: peripheral_pb.StackMapResponse.info_map:type_name -> peripheral_pb.StackMapResponse.InfoMapEntry
	1, // 2: peripheral_pb.StackMapResponse.InfoMapEntry.value:type_name -> peripheral_pb.Stack
	4, // 3: peripheral_pb.StackService.AddStack:input_type -> peripheral_pb.Location
	4, // 4: peripheral_pb.StackService.DeleteStack:input_type -> peripheral_pb.Location
	2, // 5: peripheral_pb.StackService.PushStacks:input_type -> peripheral_pb.StackMapResponse
	3, // 6: peripheral_pb.StackService.AddStack:output_type -> peripheral_pb.Empty
	3, // 7: peripheral_pb.StackService.DeleteStack:output_type -> peripheral_pb.Empty
	3, // 8: peripheral_pb.StackService.PushStacks:output_type -> peripheral_pb.Empty
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_stack_proto_init() }
func file_stack_proto_init() {
	if File_stack_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stack_proto_rawDesc), len(file_stack_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stack_proto_goTypes,
		DependencyIndexes: file_stack_proto_depIdxs,
		MessageInfos:      file_stack_proto_msgTypes,
	}.Build()
	File_stack_proto = out.File
	file_stack_proto_goTypes = nil
	file_stack_proto_depIdxs = nil
}
